{{- if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: ingress
  name: alb-ingress
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}

spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation

    - host: {{ .Values.endpoint.console_api }}
      http:
        paths:
          - backend:
              serviceName: console-api
              servicePort: 80
            path: /*

    - host: "*.{{ .Values.endpoint.console }}"
      http:
        paths:
          - backend:
              serviceName: console
              servicePort: 80
            path: /*
{{- end }}
