{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: redis 
  name: redis
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: redis
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: redis
    spec:
{{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: redis 
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}

{{- end }}
