###############################
# DEFAULT 
###############################
enabled: true

image:
    repository: spaceone
    name: spacectl
    version: 1.6.2
    imagePullPolicy: Always

# auth: local | oauth
auth: local

main:
    import:
      - /root/spacectl/apply/domain.yaml
      - /root/spacectl/apply/monitoring.yaml
      - /root/spacectl/apply/statistics.yaml

    var:
      domain_name: xxx3
      domain_owner: admin
      domain_owner_password: Admin1234567890
      oauth_plugin_id: plugin-e6b1b0bbacc6
      oauth_plugin_version: "1.1"
      oauth_plugin_domain: example.com
      oauth_plugin_client_id: 111111111111111111111111111111111111111111111.apps.googleusercontent.com
      project_admin_policy_type: MANAGED
      project_admin_policy_id: policy-0386cce2730b
      domain_admin_policy_type: MANAGED
      domain_admin_policy_id: policy-0386cce2730b
      username: user1@example.com
      password: User1234!
      aws_cloud_watch_plugin_id: plugin-41782f6158bb
      aws_cloud_watch_plugin_version: "1.1"
      google_cloud_stackdriver_plugin_id: plugin-57773973639a
      google_cloud_stackdriver_plugin_version: "1.0.3"
      azure_monitor_plugin_id: plugin-c6c14566298c
      azure_monitor_plugin_id_plugin_version: "1.0"
      aws_hyperbilling_plugin_id: plugin-38b368c8e27e
      aws_hyperbilling_version: "1.0.2"

    tasks: []

global:
    namespace: spaceone
