apiVersion: v2
name: spaceone
description: A Helm chart for SpaceONE
home: https://www.spaceone.org
type: application
version: 2.0.0-dev13
appVersion: 2.0.0
dependencies:
  - condition: console.enabled
    name: console
    repository: https://cloudforet-io.github.io/charts
    version: '1.2.17'
  - condition: console-api.enabled
    name: console-api
    repository: https://cloudforet-io.github.io/charts
    version: '1.1.12'
  - condition: identity.enabled
    name: identity
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.11'
  - condition: secret.enabled
    name: secret
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.13'
  - condition: repository.enabled
    name: repository
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.11'
  - condition: plugin.enabled
    name: plugin
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.11'
  - condition: config.enabled
    name: config
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.10'
  - condition: inventory.enabled
    name: inventory
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.19'
  - condition: monitoring.enabled
    name: monitoring
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.24'
  - condition: statistics.enabled
    name: statistics
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.16'
  - condition: cost-analysis.enabled
    name: cost-analysis
    repository: https://cloudforet-io.github.io/charts
    version: '1.4.0'
  - condition: notification.enabled
    name: notification
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.16'
  - condition: board.enabled
    name: board
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.12'
  - condition: file-manager.enabled
    name: file-manager
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.6'
  - condition: dashboard.enabled
    name: dashboard
    repository: https://cloudforet-io.github.io/charts
    version: '1.3.12'
  - condition: console-api-v2.enabled
    name: console-api-v2
    repository: https://cloudforet-io.github.io/charts
    version: '1.0.8'
  - condition: supervisor.enabled
    name: supervisor
    repository: https://cloudforet-io.github.io/charts
    version: '1.1.15'
  - condition: marketplace-assets.enabled
    name: marketplace-assets
    repository: https://cloudforet-io.github.io/charts
    version: '>=1.0.0'
  - condition: spacectl.enabled
    name: spacectl
    repository: https://cloudforet-io.github.io/charts
    version: '>=1.0.0'
