#######################################
# Configuration of spaceone
#######################################
enabled: true
image:
    name: alpine
    version: 3.3

resources: {}
#     requests:
#         memory: "128Mi"
#         cpu: "25m"
#     limits:
#         memory: "256Mi"
#         cpu: "50m"

# imagePullSecrets:
#   - name: <name of imagePullSecret>

#######################################
# Configuration of sub-charts
#######################################

# Service
mongodb:
    enabled: false
    resources: {}
    #     requests:
    #         memory: "128Mi"
    #         cpu: "25m"
    #     limits:
    #         memory: "256Mi"
    #         cpu: "50m"

redis:
    enabled: true
    resources: {}
    #     requests:
    #         memory: "128Mi"
    #         cpu: "25m"
    #     limits:
    #         memory: "256Mi"
    #         cpu: "50m"

consul:
    enabled: false
    connectInject:
        enabled: false

# for Developer, instead of AWS SecretsManager
vault:
    enabled: false
    resources: {}
    #     requests:
    #         memory: "128Mi"
    #         cpu: "25m"
    #     limits:
    #         memory: "256Mi"
    #         cpu: "50m"

console:
    enable: true
    image:
        name: spaceone/console
        version: 1.10.4

console-api:
    enable: true
    image:
        name: spaceone/console-api
        version: 1.10.4

identity:
    enabled: true
    image:
        name: spaceone/identity
        version: 1.10.4
    application_grpc: {}

secret:
    enabled: true
    image:
        name: spaceone/secret
        version: 1.10.4
    application_grpc: {}


#    application:
#        CONNECTORS:
#            AWSSecretManagerConnector:
#                aws_access_key_id: aaaaaaaaaaaaaaaaaaaa
#                aws_secret_access_key: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
#                region_name: us-west-1
#
# Note: VaultConnector is for only developer
#           VaultConnector:
#               url: http://vault:8200
#               token: myroot
repository:
    enabled: true
    image:
        name: spaceone/repository
        version: 1.10.4

    application_grpc: {}

#    application:
#        ROOT_TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
#        CONNECTORS:
#            RegistryConnector:
#                host: https://257706363616.dkr.ecr.ap-northeast-2.amazonaws.com
#                verify_ssl: False
#                api_version: 2
#                username: AWS

plugin:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/plugin
        version: 1.10.4

    application_grpc: {}

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

config:
    enabled: true
    image:
        name: spaceone/config
        version: 1.10.4

    application_grpc: {}

inventory:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/inventory
        version: 1.10.4

    application_grpc: {}

#    application:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
#        collect_queue: collector_q

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN


monitoring:
    enabled: true
    scheduler: false
    worker: false
    rest: false 
    replicas: 1         # replica number of grpc server
    replicas_worker: 1  # replica number of worker server
    image:
        name: spaceone/monitoring
        version: 1.10.4

    application_grpc:
        WEBHOOK_DOMAIN: https://monitoring-webhook

#    application_rest:
#        #TOKEN: XXXXXXXXXXXXX (if you want to use instead of TOKEN_INFO)
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

#    application_scheduler:
#        #TOKEN: XXXXXXXXXXXXX (if you want to use instead of TOKEN_INFO)
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

statistics:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/statistics
        version: 1.10.4

    application_grpc: {}

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

cost-analysis:
    enabled: true
    image:
        name: spaceone/cost-analysis
        version: 1.10.4

    application_grpc: {}

notification:
    enabled: true
    image:
        name: spaceone/notification
        version: 1.10.4

    application_grpc: {}

board:
    enabled: true
    image:
        name: spaceone/board
        version: 1.10.4

file-manager:
    enabled: true
    image:
        name: spaceone/file-manager
        version: 1.10.4

supervisor:
    enabled: true
    image:
        name: spaceone/supervisor
        version: 1.10.4

spaceone-initializer:
    enabled: false
    image:
        version: 1.10.4

domain-initialzer:
    enabled: false

global:
    namespace: spaceone
    supervisor_namespace: root-supervisor
    backend:
        sidecar: []
        volumes: []
    frontend:
        sidecar: []
        volumes: []
    shared_conf:
        HANDLERS:
            authentication:
            - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
              uri: grpc://identity:50051/v1/Domain/get_public_key
            authorization:
            - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
              uri: grpc://identity:50051/v1/Authorization/verify
            mutation:
            - backend: spaceone.core.handler.mutation_handler.SpaceONEMutationHandler
        CONNECTORS:
            IdentityConnector:
                endpoint:
                    v1: grpc://identity:50051
            SecretConnector:
                endpoint:
                    v1: grpc://secret:50051
            RepositoryConnector:
                endpoint:
                    v1: grpc://repository:50051
            PluginConnector:
                endpoint:
                    v1: grpc://plugin:50051
            ConfigConnector:
                endpoint:
                    v1: grpc://config:50051
            InventoryConnector:
                endpoint:
                    v1: grpc://inventory:50051
            MonitoringConnector:
                endpoint:
                    v1: grpc://monitoring:50051
            StatisticsConnector:
                endpoint:
                    v1: grpc://statistics:50051
            NotificationConnector:
                endpoint:
                    v1: grpc://notification:50051
        CACHES:
            default:
                backend: spaceone.core.cache.redis_cache.RedisCache
                host: redis
                port: 6379
                db: 0
                encoding: utf-8
                socket_timeout: 10
                socket_connect_timeout: 10
