enabled: true

# Service
mongodb:
    enabled: false
redis:
    enabled: true
consul:
    enabled: false

# for Developer, instead of aWS SecretsManager
vault:
    enabled: false

console:
    enable: true
    image:
        name: spaceone/console
        version: 1.7.1

console-api:
    enable: true
    image:
        name: spaceone/console-api
        version: 1.7.1


identity:
    enabled: true
    image:
        name: spaceone/identity
        version: 1.7.1
    application_grpc: {}

secret:
    enabled: true
    image:
        name: spaceone/secret
        version: 1.7.1
    application_grpc: {}


#    application:
#        CONNECTORS:
#            AWSSecretManagerConnector:
#                aws_access_key_id: aaaaaaaaaaaaaaaaaaaa
#                aws_secret_access_key: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
#                region_name: us-west-1
#
# Note: VaultConnector is for only developer
#           VaultConnector:
#               url: http://vault:8200
#               token: myroot
repository:
    enabled: true
    image:
        name: spaceone/repository
        version: 1.7.1

    application_grpc: {}

#    application:
#        ROOT_TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
#        CONNECTORS:
#            RegistryConnector:
#                host: https://257706363616.dkr.ecr.ap-northeast-2.amazonaws.com
#                verify_ssl: False
#                api_version: 2
#                username: AWS

plugin:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/plugin
        version: 1.7.1

    application_grpc: {}

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

config:
    enabled: true
    image:
        name: spaceone/config
        version: 1.7.1

    application_grpc: {}

inventory:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/inventory
        version: 1.7.1

    application_grpc: {}

#    application:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
#        collect_queue: collector_q

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN


monitoring:
    enabled: true
    image:
        name: spaceone/monitoring
        version: 1.7.1

    application_grpc: {}

statistics:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/statistics
        version: 1.7.1

    application_grpc: {}

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN


billing:
    enabled: true
    image:
        name: spaceone/billing
        version: 1.7.1

    application_grpc: {}

power-scheduler:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/power-scheduler
        version: 1.7.1

    application_grpc: {}

cost-saving:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/cost-saving
        version: 1.7.1

    application_grpc: {}

spot-automation:
    enabled: true
    scheduler: true
    worker: true
    image:
        name: spaceone/spot-automation
        version: 1.7.1

    application_grpc: {}

#    application_scheduler:
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN


# include config/alb.yaml (for ALB)
# include config/nlb.yaml (for NLB)
supervisor:
    enabled: true
    image:
        name: spaceone/supervisor
        version: 1.7.1


spaceone-initializer:
    enabled: false
    image:
        version: 1.7.1

domain-initialzer:
    enabled: false

global:
    namespace: spaceone
    supervisor_namespace: root-supervisor
    backend:
        sidecar: []
        volumes: []
    frontend:
        sidecar: []
        volumes: []
