###############################
# DEFAULT 
###############################
enabled: true
image:
    name: mongo
imagePullPolicy: IfNotPresent
username: admin
password: password
service:
    type: ClusterIP
    ports:
        - name: mongodb
          port: 27017
          targetPort: 27017
          protocol: TCP
pvc:
    enabled: false
    storageClassName: null # `null` value will use the Kubernetes cluster's default StorageClass
    accessModes: 
        - "ReadWriteOnce"
    requests:
        storage: 8Gi