console:
  image:
    version: 1.6.2.1
console-api:
  image:
    version: 1.6.2.1
identity:
  image:
    version: 1.6.4-rc3
    repository: pyengine
secret:
  image:
    version: 1.6.2.1.20210301.002212
    repository: pyengine
repository:
  image:
    version: 1.6.4-rc1.20210301.002800
plugin:
  image:
    version: 1.6.2
config:
  image:
    version: 1.6.2.1
inventory:
  image:
    version: 1.6.2.6
monitoring:
  image:
    version: 1.6.2.1
statistics:
  image:
    version: 1.6.2.1
billing:
  image:
    version: 1.6.2
power-scheduler:
  image:
    version: 1.6.2
supervisor:
  image:
    version: 1.6.4
