{{ if .Values.enabled }}
{{- $main := toYaml .Values.main -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-spacectl-main-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  main.yaml: |-
{{ tpl $main . | indent 4 }}
{{ end }}
