{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: consul 
  name: consul
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: consul
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: consul
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: consul 
          image: bitnami/consul:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}

{{- end }}
