{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: consul
  name: consul
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    spaceone.service: consul
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{ end }}
