name: "[actions]only_pypi"
on:
  workflow_dispatch:

jobs:

# docker/pypi : identity, inventory, monitoring, repository, statistics, secret, config, supervisor, plugin
# docker만 : console-assets, custom-report, console-api, console
# pypi만 : api, python-core
  all_in_one_update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          git config --global user.email admin@spaceone.dev
          git config --global user.name admin-spaceone
          eval "$(ssh-agent -s)"
          cat <<EOF>id_rsa
          ${{secrets.ssh_key}}
          EOF
          chmod 400 ./id_rsa && ssh-add ./id_rsa
          git pull
          git clone git@github.com:spaceone-dev/python-core.git
          \cp -rf github_actions/common/workflows/* python-core/.github/workflows
          rm -f python-core/.github/workflows/\[CI\]master\ push.yml
          \cp -rf github_actions/only_pypi/python-core/* python-core/.github/workflows
          cd python-core
          git add . && git commit -m "[CI/CD] update github actions" && git push
          cd ..
          git clone git@github.com:spaceone-dev/api.git
          \cp -rf github_actions/only_pypi/api/* api/.github/workflows
          cd api
          git add . && git commit -m "[CI/CD] update github actions" && git push

  notify_to_slack:
    if: github.repository_owner == 'spaceone-dev'
    needs: [all_in_one_update]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
