name: "[plugins]update actions"
on:
  workflow_dispatch:

jobs:
  all_in_one_update_public:
    strategy:
      fail-fast: false
      matrix:
        target: ['plugin-aws-cloudservices', 'plugin-aws-ec2', 'plugin-googlecloud-compute', 'plugin-aws-cloudwatch', 'plugin-aws-trustedadvisor', 'plugin-googlecloud-stackdriver', 'plugin-aws-health', 'plugin-google-cloud-services', 'plugin-google-cloud-power-scheduler-controller']
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: set token
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: task
        env:
          target: ${{ matrix.target }}
        run: |
          git config --global user.email admin@spaceone.dev
          git config --global user.name admin-spaceone
          eval "$(ssh-agent -s)"
          cat <<EOF>id_rsa
          ${{secrets.ssh_key}}
          EOF
          chmod 400 ./id_rsa && ssh-add ./id_rsa
          git pull
          git clone git@github.com:spaceone-dev/${{ env.target }}.git
          mkdir -p ${{ env.target }}/.github/workflows
          \cp -f github_actions/plugins/public/* ${{ env.target }}/.github/workflows
          cd ${{ env.target }}
          git add . && git commit -m "[CI/CD] update github actions" && git push
          cd ..

  notify_to_slack:
    if: github.repository_owner == 'spaceone-dev'
    needs: [all_in_one_update_public]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
