name: "[update]back test"
on:
  workflow_dispatch:

jobs:

# docker/pypi : identity, inventory, monitoring, repository, statistics, secret, config, supervisor, plugin
# docker만 : console-assets, custom-report, console-api, console
# pypi만 : api, python-core
  all_in_one_update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          git config --global user.email admin@spaceone.dev
          git config --global user.name admin-spaceone
          eval "$(ssh-agent -s)"
          cat <<EOF>id_rsa
          ${{secrets.ssh_key}}
          EOF
          chmod 400 ./id_rsa && ssh-add ./id_rsa
          git pull
          git clone git@github.com:spaceone-dev/identity.git
          \cp -rf github_actions/common/workflows identity/.github/
          \cp -rf github_actions/backend/workflows identity/.github/
          cd identity
          git add . && git commit -m "[CI/CD] update github actions" && git push